# 正式环境数据源
spring: 
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.x.y:3306/crawler_db?serverTimezone=Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: user
    password: pwd
  