mybatis:  
  # 开发 环境在控制台打印sql
  configuration: 
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 日志配置
logging: 
  level: 
    com.efe.ms.crawlerservice.dao: debug
    com.efe.ms.crawlerservice.mongorepo: info